<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>LAVAL — Mantel Configurator</title>
  <meta name="description" content="LAVAL mantel configurator — Premium static configurator prototype.">
  <meta name="robots" content="noindex,nofollow">

  <!--
    Typography law: Cormorant Garamond for editorial hierarchy + Inter for UI.
    External font loading is attempted via Google Fonts. If unreachable, the
    proper font stacks in styles.css fall through to system serif/sans.
    No font files are bundled with the prototype.
  -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,500;0,600;1,300&family=Inter:wght@300;400;500&display=swap">

  <link rel="stylesheet" href="styles.css">
</head>
<body>

  <!--
    LavalConfiguratorShell — root viewport. Every shell zone is a direct
    child of .laval-shell so anchors are screen-space, not page-flow.
    Subject and connector layers sit beneath HUD; HUD sits above stage.
  -->
  <div class="laval-shell" id="laval-shell" data-shell-state="wide">

    <!-- World shell: deep warm charcoal field, fog, floor glow -->
    <div class="laval-world" aria-hidden="true">
      <div class="laval-world-floor"></div>
      <div class="laval-world-fog"></div>
      <div class="laval-world-vignette"></div>
    </div>

    <!--
      Zone 6 — ProtectedMantelStage
      Center stage holds the staged-2D mantel composition. No HUD zone may
      invade this region per LAVAL Forensic Spec v7 §C OBJ-11.
      Phase 1 ships an inline SVG silhouette, not a generic rectangle.
    -->
    <main class="laval-stage" aria-label="Mantel preview stage">
      <figure class="laval-stage-figure"
              id="laval-stage-figure"
              data-family="tailored-classical"
              data-profile=""
              data-leg=""
              data-shelf=""
              data-finish="">
        <!--
          Layered 2D mantel preview. Inline SVG is regenerated by
          renderMantelPreview() on every selection change. data-* attributes
          on the figure mirror the active state so CSS can theme overlays.
        -->
        <div class="laval-mantel-mount" id="laval-mantel-mount" role="img"
             aria-label="Mantel preview"></div>
        <figcaption class="laval-stage-caption">
          <span class="laval-stage-caption-eyebrow">Preview</span>
          <span class="laval-stage-caption-text" id="laval-stage-caption-text">Tailored Classical · Select options to refine</span>
        </figcaption>
      </figure>
    </main>

    <!--
      Zone 1 — TopNavCluster
      Quiet upper-left back/location/title cluster on the top governance band.
    -->
    <nav class="laval-top-nav" aria-label="Workspace breadcrumb">
      <button class="laval-top-nav-back" type="button" aria-label="Back to workspace">
        <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
          <path d="M10 3 L5 8 L10 13" fill="none" stroke="currentColor"
                stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span>Workspace</span>
      </button>
      <span class="laval-top-nav-divider" aria-hidden="true">·</span>
      <span class="laval-top-nav-title">Mantel Configurator</span>
    </nav>

    <!--
      Zone 2 — TopUtilityCapsule
      Top-center utility cluster: Undo / Redo / Reset / Save Draft.
      Phase 1: static, non-functional (no state to undo yet).
    -->
    <div class="laval-top-utility" role="toolbar" aria-label="Editing utilities">
      <button class="laval-utility-btn" type="button" aria-label="Undo" disabled>
        <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
          <path d="M4 8 H11 a3 3 0 0 1 0 6 H7 M4 8 L7 5 M4 8 L7 11"
                fill="none" stroke="currentColor" stroke-width="1.25"
                stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>
      <button class="laval-utility-btn" type="button" aria-label="Redo" disabled>
        <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
          <path d="M12 8 H5 a3 3 0 0 0 0 6 H9 M12 8 L9 5 M12 8 L9 11"
                fill="none" stroke="currentColor" stroke-width="1.25"
                stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>
      <span class="laval-utility-sep" aria-hidden="true"></span>
      <button class="laval-utility-btn" type="button" aria-label="Reset selection" disabled>
        <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
          <path d="M3 8 a5 5 0 1 0 1.5 -3.5 M3 3 V5 H5"
                fill="none" stroke="currentColor" stroke-width="1.25"
                stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>
      <button class="laval-utility-btn" type="button" aria-label="Save draft" disabled>
        <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
          <path d="M3 3 H11 L13 5 V13 H3 Z M5 3 V7 H10 V3 M5 13 V10 H11 V13"
                fill="none" stroke="currentColor" stroke-width="1.25"
                stroke-linejoin="round"/>
        </svg>
      </button>
    </div>

    <!--
      Zone 3 — TopRightReviewPill
      Brighter accent pill on the upper-right; same glass family.
      Phase 1: visual only, non-functional.
    -->
    <button class="laval-top-pill" type="button" disabled>
      <span class="laval-top-pill-label">Request Pricing</span>
      <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
        <path d="M5 3 L10 8 L5 13" fill="none" stroke="currentColor"
              stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </button>

    <!--
      Zone 4 — LeftSemanticPane
      Tall left-side explanatory pane. Phase 1: static summary text only.
    -->
    <aside class="laval-left-pane" aria-label="Step context">
      <div class="laval-pane-header">
        <span class="laval-eyebrow" id="laval-pane-eyebrow">Step 01</span>
        <h1 class="laval-pane-title" id="laval-pane-title">Mantel Family</h1>
      </div>
      <p class="laval-pane-body" id="laval-pane-helper">
        Choose the architectural family that anchors the mantel. The family
        sets the silhouette grammar; later steps refine profile, legs, shelf,
        and stone finish without restyling the whole composition.
      </p>

      <div class="laval-pane-divider" aria-hidden="true"></div>

      <div class="laval-pane-summary">
        <span class="laval-eyebrow">Selection so far</span>
        <ul class="laval-pane-summary-list">
          <li class="laval-pane-summary-item is-empty">
            <span class="laval-pane-summary-key">Family</span>
            <span class="laval-pane-summary-val">—</span>
          </li>
          <li class="laval-pane-summary-item is-empty">
            <span class="laval-pane-summary-key">Profile</span>
            <span class="laval-pane-summary-val">—</span>
          </li>
          <li class="laval-pane-summary-item is-empty">
            <span class="laval-pane-summary-key">Leg</span>
            <span class="laval-pane-summary-val">—</span>
          </li>
          <li class="laval-pane-summary-item is-empty">
            <span class="laval-pane-summary-key">Shelf</span>
            <span class="laval-pane-summary-val">—</span>
          </li>
          <li class="laval-pane-summary-item is-empty">
            <span class="laval-pane-summary-key">Finish</span>
            <span class="laval-pane-summary-val">—</span>
          </li>
        </ul>
      </div>
    </aside>

    <!--
      Zone 5 — MantelStepRail
      Near-subject vertical rail of five orbs. Array-driven from
      prototype/data/options.js via app.js.
    -->
    <nav class="laval-step-rail" aria-label="Configurator steps">
      <ul class="laval-step-rail-list" id="laval-step-rail-list">
        <!-- StepRailOrb children rendered by app.js from STEPS -->
      </ul>
    </nav>

    <!--
      Zone 7 — RightOptionBrowser
      Primary right-side option browsing region with a header utility row
      and a tile grid body. Phase 1 ships static placeholder family tiles.

      Zone 8 — Nested Editor Envelope Slot
      Empty mount point inside the browser. Phase 1 renders nothing here.
    -->
    <aside class="laval-right-browser" aria-label="Options">
      <header class="laval-browser-header">
        <div class="laval-browser-header-titles">
          <span class="laval-eyebrow">Options</span>
          <h2 class="laval-browser-title" id="laval-browser-title">Family</h2>
        </div>
        <div class="laval-browser-header-tools" role="toolbar" aria-label="Browser tools">
          <button class="laval-browser-tool" type="button" aria-label="Filter" disabled>
            <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
              <path d="M3 4 H13 L10 9 V13 L6 12 V9 Z"
                    fill="none" stroke="currentColor" stroke-width="1.25"
                    stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </button>
          <button class="laval-browser-tool" type="button" aria-label="More" disabled>
            <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
              <circle cx="4" cy="8" r="1" fill="currentColor"/>
              <circle cx="8" cy="8" r="1" fill="currentColor"/>
              <circle cx="12" cy="8" r="1" fill="currentColor"/>
            </svg>
          </button>
        </div>
      </header>

      <div class="laval-browser-body">
        <ul class="laval-browser-grid" id="laval-browser-grid">
          <!-- FAMILY_TILES rendered by app.js -->
        </ul>
      </div>

      <!-- Nested editor envelope slot — empty in Phase 1 -->
      <div class="laval-editor-slot"
           id="laval-editor-slot"
           data-mounted="false"
           hidden
           aria-hidden="true">
      </div>
    </aside>

    <!--
      Zone 9 — BottomWidgetDock
      Three grouped zones: descriptive state · compact widget dock · advance.
      Distinct widgets, hairline separators, low-profile.
    -->
    <div class="laval-bottom-dock" role="toolbar" aria-label="Step progress and advance">
      <div class="laval-dock-state">
        <span class="laval-dock-state-eyebrow">Step</span>
        <span class="laval-dock-state-text" id="laval-dock-step-text">01 of 05 · Family</span>
      </div>

      <span class="laval-dock-sep" aria-hidden="true"></span>

      <div class="laval-dock-widgets" id="laval-dock-widgets">
        <!-- StepRailOrb micro-tokens rendered by app.js -->
      </div>

      <span class="laval-dock-sep" aria-hidden="true"></span>

      <button class="laval-dock-advance" type="button" disabled>
        <span>Continue</span>
        <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
          <path d="M5 3 L10 8 L5 13" fill="none" stroke="currentColor"
                stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>
    </div>

    <!--
      Zone 10 — FocusConnectorLayer
      Empty overlay layer; hidden by default. Phase 4 activates the connector
      line and orb-node guidance subsystem. Evidence and mapping details are
      in source_evidence_log.md and laval_component_map.json.
    -->
    <svg class="laval-connector-layer"
         id="laval-connector-layer"
         viewBox="0 0 100 100"
         preserveAspectRatio="none"
         aria-hidden="true"
         hidden>
      <!-- Phase 4 will draw connector lines + orb nodes here -->
    </svg>

    <!-- ===================================================================
      Phase 6 — Review state / lead-capture sheet
      Shown when user clicks "Review" on Step 5 with a Finish selection.
      Remains inside the shell — not a new page, not a full-screen modal.
      Top nav stays visible; shell identity preserved.
    =================================================================== -->
    <div class="laval-review-sheet"
         id="laval-review-sheet"
         role="dialog"
         aria-modal="false"
         aria-label="Review selection and request pricing"
         hidden>

      <!-- Review header -->
      <div class="laval-review-header">
        <div class="laval-review-header-text">
          <span class="laval-eyebrow">Step 06</span>
          <h2 class="laval-review-title">Review &amp; Request Pricing</h2>
        </div>
        <button class="laval-review-back" id="laval-review-back" type="button">
          <svg class="laval-glyph" viewBox="0 0 16 16" aria-hidden="true">
            <path d="M10 3 L5 8 L10 13" fill="none" stroke="currentColor"
                  stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          <span>Back to Configurator</span>
        </button>
      </div>

      <!-- Review body: summary + form side by side -->
      <div class="laval-review-body">

        <!-- Selection summary panel -->
        <div class="laval-review-summary">
          <h3 class="laval-review-section-title">Your Selection</h3>
          <ul class="laval-review-summary-list" id="laval-review-summary-list">
            <!-- Populated by activateReviewState() -->
          </ul>
          <p class="laval-review-note">
            This is an architectural preview. Final specifications and
            stone availability are confirmed by our studio.
          </p>
        </div>

        <!-- Divider -->
        <div class="laval-review-divider" aria-hidden="true"></div>

        <!-- Request Pricing form -->
        <div class="laval-review-form-wrap">
          <h3 class="laval-review-section-title">Request Pricing</h3>

          <!-- Confirmation (shown after submit) -->
          <div class="laval-review-confirm" id="laval-review-confirm" hidden>
            <p class="laval-review-confirm-text">
              Request received. We'll be in touch.
            </p>
            <p class="laval-review-confirm-sub">
              Our studio will contact you within two business days.
            </p>
          </div>

          <!-- Form -->
          <form class="laval-review-form" id="laval-review-form" novalidate>
            <div class="laval-form-field">
              <label class="laval-form-label" for="laval-field-name">Name <span class="laval-form-req" aria-hidden="true">*</span></label>
              <input
                class="laval-form-input"
                id="laval-field-name"
                name="name"
                type="text"
                autocomplete="name"
                required
                placeholder="Your full name"
                aria-required="true"/>
            </div>
            <div class="laval-form-field">
              <label class="laval-form-label" for="laval-field-email">Email <span class="laval-form-req" aria-hidden="true">*</span></label>
              <input
                class="laval-form-input"
                id="laval-field-email"
                name="email"
                type="email"
                autocomplete="email"
                required
                placeholder="your@email.com"
                aria-required="true"/>
            </div>
            <div class="laval-form-field">
              <label class="laval-form-label" for="laval-field-phone">Phone <span class="laval-form-opt">(optional)</span></label>
              <input
                class="laval-form-input"
                id="laval-field-phone"
                name="phone"
                type="tel"
                autocomplete="tel"
                placeholder="(optional)"/>
            </div>
            <div class="laval-form-field">
              <label class="laval-form-label" for="laval-field-message">Message <span class="laval-form-opt">(optional)</span></label>
              <textarea
                class="laval-form-input laval-form-textarea"
                id="laval-field-message"
                name="message"
                rows="3"
                placeholder="Installation timeline, project context, or questions..."></textarea>
            </div>
            <p class="laval-form-req-note"><span aria-hidden="true">*</span> Required fields</p>
            <button class="laval-form-submit" id="laval-form-submit" type="submit">
              Request Pricing
            </button>
          </form>
        </div>

      </div><!-- /.laval-review-body -->
    </div><!-- /#laval-review-sheet -->

  </div><!-- /.laval-shell -->

  <script type="module" src="app.js"></script>
</body>
</html>
